import "./globals.css";
import { CryptoProvider } from "./context/CryptoContext";


export const metadata = {
  title: "CryptoDashboard App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <CryptoProvider>
      <body  style={{ margin: 0, minHeight: "100vh", display: "flex",alignItems:"center", flexDirection: "column" }} >
        {children}
      </body>
      </CryptoProvider>
    </html>
  );
}
